---
- name: Deploy Java App on Docker
  hosts: allhosts
  become: true  # Use sudo if Docker needs root privileges
  tasks:
    - name: Ensure existing container is absent
      community.docker.docker_container:
        name: java_container
        state: absent

    - name: Run new Docker container
      community.docker.docker_container:
        name: java_container
        image: javaimg:latest
        state: started
        detach: true

    - name: Get container logs
      command: docker logs java_container
      register: container_logs

    - name: Display container output
      debug:
        msg: "{{ container_logs.stdout_lines }}"
